name: Android Build

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Pull request on master or develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build Project
        run: ./gradlew assemble

      - name: Apk name
        id: apk
        uses: emm3000/apk-name-action@v1.4
        with:
          pull-request-name: ${{ github.event.pull_request.title }}

      - name: Print
        run: echo ${{ github.event.pull_request.title }} aea

#      - uses: actions/upload-artifact@v3
#        with:
#          name: ${{ steps.apk.outputs.apk-name }}
#          path: ./app/build/outputs/apk/debug
##
#      - name: Run Tests
#        run: ./gradlew test
#
#      - name: Lint Checks
#        run: ./gradlew ktlintCheck detekt